[package]
edition = "2018"
name = "web-tree-sitter-sys"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/darinmorrison/web-tree-sitter-sys"
description = """
Raw bindings to the tree-sitter-web API.
"""

[badges]
maintenance = { status = "experimental" }

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false
test = false

# [profile.dev]
# codegen-units = 1
# lto = "thin"
# opt-level = 'z'
# panic = 'abort'

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 'z'
panic = 'abort'

[features]
default = ["wee_alloc"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = { version = "0.2", features = ["strict-macro"] }
wee_alloc = { version = "0.4", optional = true }

[dependencies.web-sys]
version = "0.3"

[dev-dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"

[workspace]
members = [".", "xtask"]
default-members = ["."]
